version: "3"

services:
  apollo-server:
    container_name: apollo-server
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
